Update CommentItem.vue
halo-sigs/plugin-comment-widget pull request #47
Opened 2023-07-10 03:44 UTC by wsj20010128

Change <p> to <pre>

2023-07-10 04:32 UTC, LIlGG commented
/lgtm

<img width="328" alt="image" src="https://github.com/halo-sigs/plugin-comment-widget/assets/31335418/8dd128bc-bf80-48e3-b62d-1346359b6ccb">

2023-07-10 04:33 UTC, LIlGG commented
/lgtm

2023-07-10 04:37 UTC, ruibaby requested changes
ReplyItem 应该也需要做同样的修改。

2023-07-12 16:06 UTC, ruibaby approved these changes
/lgtm

2023-07-12 16:07 UTC, merged